/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas;

import java.awt.Color;
import java.awt.Component;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.codegen.CompilerConstants;
import sun.security.util.ArrayUtil;
import sun.text.resources.iw.CollationData_iw;

/**
 *
 * @author PC
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     * 
     *
     */
    private int lengthInput = 0;
    private final String[] operator = {"*", "/", "+", "-"};
    private int jumOperator = 0;
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Output = new javax.swing.JTextField();
        angka7 = new javax.swing.JButton();
        angka8 = new javax.swing.JButton();
        angka9 = new javax.swing.JButton();
        angka4 = new javax.swing.JButton();
        angka5 = new javax.swing.JButton();
        angka6 = new javax.swing.JButton();
        angka1 = new javax.swing.JButton();
        angka2 = new javax.swing.JButton();
        angka3 = new javax.swing.JButton();
        angka0 = new javax.swing.JButton();
        titik = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);

        Output.setFont(new java.awt.Font("Lora", 1, 24)); // NOI18N
        Output.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Output.setText("0");
        Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputActionPerformed(evt);
            }
        });

        angka7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        angka7.setText("7");
        angka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka7ActionPerformed(evt);
            }
        });

        angka8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        angka8.setText("8");
        angka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka8ActionPerformed(evt);
            }
        });

        angka9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        angka9.setText("9");
        angka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka9ActionPerformed(evt);
            }
        });

        angka4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        angka4.setText("4");
        angka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka4ActionPerformed(evt);
            }
        });

        angka5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        angka5.setText("5");
        angka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka5ActionPerformed(evt);
            }
        });

        angka6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        angka6.setText("6");
        angka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka6ActionPerformed(evt);
            }
        });

        angka1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        angka1.setText("1");
        angka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka1ActionPerformed(evt);
            }
        });

        angka2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        angka2.setText("2");
        angka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka2ActionPerformed(evt);
            }
        });

        angka3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        angka3.setText("3");
        angka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka3ActionPerformed(evt);
            }
        });

        angka0.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        angka0.setText("0");
        angka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka0ActionPerformed(evt);
            }
        });

        titik.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });

        btnBagi.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnBagi.setText("/");
        btnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagiActionPerformed(evt);
            }
        });

        kali.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        kali.setText("*");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });

        kurang.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });

        tambah.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        samadengan.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Output)
                    .addComponent(samadengan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(angka7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(angka8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(angka9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(angka1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(angka2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(angka3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(angka0, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(titik, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(angka4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(angka5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(angka6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kali, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(angka7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(angka8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(angka9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(angka4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(angka5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(angka6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(angka1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(angka2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(angka3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(angka0, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titik, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(kali, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(samadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputActionPerformed

    }//GEN-LAST:event_OutputActionPerformed

    private void angka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka8ActionPerformed
        setAngka("8");
    }//GEN-LAST:event_angka8ActionPerformed

    private void angka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka5ActionPerformed
        setAngka("5");
    }//GEN-LAST:event_angka5ActionPerformed

    private void angka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka2ActionPerformed
        setAngka("2");
    }//GEN-LAST:event_angka2ActionPerformed

    private void angka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka7ActionPerformed
        setAngka("7");
    }//GEN-LAST:event_angka7ActionPerformed

    private void angka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka4ActionPerformed
        setAngka("4");
    }//GEN-LAST:event_angka4ActionPerformed

    private void angka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka6ActionPerformed
        setAngka("6"); 
    }//GEN-LAST:event_angka6ActionPerformed

    private void angka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka1ActionPerformed
        setAngka("1");
    }//GEN-LAST:event_angka1ActionPerformed

    private void angka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka3ActionPerformed
        setAngka("3");
    }//GEN-LAST:event_angka3ActionPerformed

    private void angka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka0ActionPerformed
        setAngka("0");
    }//GEN-LAST:event_angka0ActionPerformed

    private void angka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka9ActionPerformed
        setAngka("9");
    }//GEN-LAST:event_angka9ActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        //mengecek apakah ada operator pada inputan terakhir
        if (Arrays.asList(operator).contains(String.valueOf(Output.getText().charAt(Output.getText().length()-1)))) {
            JOptionPane.showMessageDialog(this, "Masukkan angka setelah operand");
            return;
        }
        //mengecek apakah ada operand pada inputan
        boolean checkOperandEmpty = true;
        for(char c : Output.getText().toCharArray()){
            //jika tidak ada operant maka tidak melakukan apapun
             if(Arrays.asList(operator).contains(String.valueOf(c))){
                 checkOperandEmpty = false;
                 break;
             }
         }
        //jika tidak ada operand hentikan program ==>
        if(checkOperandEmpty){
            JOptionPane.showMessageDialog(this, "masukkan operator terlebih dahulu");
            return;
        }
        //<==
        String operand = "";
         for(char c : Output.getText().toCharArray()){
            //jika tidak ada operant maka tidak melakukan apapun
             if(Arrays.asList(operator).contains(String.valueOf(c))){
                 operand = String.valueOf(c);
                 break;
             }
         }
         //karena character * dan + sudah dipesan oleh regex maka harus menambahkan \\ untuk mengidentifikasi operator
         if(operand.equals("+")|| operand.equals("*")) operand = "\\" + operand;
         String[] inputan = Output.getText().toString().split(operand);
         double hasil =0;
         
         //menghilangkan karakter titik dibelakang
         inputan[0] = fixKata(inputan[0]);
         inputan[1] = fixKata(inputan[1]);
         
         
         if (operand.equals("\\+")) {
            hasil = Double.parseDouble(inputan[0]) + Double.parseDouble(inputan[1]);
        }else if(operand.equals("-")){
            hasil = Double.parseDouble(inputan[0]) - Double.parseDouble(inputan[1]);
        }else if(operand.equals("\\*")){
            hasil = Double.parseDouble(inputan[0]) * Double.parseDouble(inputan[1]);
        }else if(operand.equals("/")){
            hasil = Double.parseDouble(inputan[0]) / Double.parseDouble(inputan[1]);
        }
         Output.setText(String.valueOf(hasil));
         jumOperator = 0;
         
    }//GEN-LAST:event_samadenganActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
        setAngka(".");
    }//GEN-LAST:event_titikActionPerformed

    private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
        setAngka("/");
    }//GEN-LAST:event_btnBagiActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        setAngka("*");
    }//GEN-LAST:event_kaliActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        setAngka("-");
    }//GEN-LAST:event_kurangActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        setAngka("+");
    }//GEN-LAST:event_tambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Kalkulator kalkulator = new Kalkulator();
                kalkulator.setVisible(true);
                kalkulator.getContentPane().setBackground(Color.BLACK);
                kalkulator.Output.setBackground(Color.BLACK);
                kalkulator.Output.setBorder(javax.swing.BorderFactory.createEmptyBorder());
                kalkulator.Output.setForeground(Color.WHITE);
                kalkulator.angka0.setBackground(Color.decode("#25262A"));
                kalkulator.angka0.setForeground(Color.WHITE);
                kalkulator.angka1.setBackground(Color.decode("#25262A"));
                kalkulator.angka1.setForeground(Color.WHITE);
                kalkulator.angka2.setBackground(Color.decode("#25262A"));
                kalkulator.angka2.setForeground(Color.WHITE);
                kalkulator.angka3.setBackground(Color.decode("#25262A"));
                kalkulator.angka3.setForeground(Color.WHITE);
                kalkulator.angka4.setBackground(Color.decode("#25262A"));
                kalkulator.angka4.setForeground(Color.WHITE);
                kalkulator.angka5.setBackground(Color.decode("#25262A"));
                kalkulator.angka5.setForeground(Color.WHITE);
                kalkulator.angka6.setBackground(Color.decode("#25262A"));
                kalkulator.angka6.setForeground(Color.WHITE);
                kalkulator.angka7.setBackground(Color.decode("#25262A"));
                kalkulator.angka7.setForeground(Color.WHITE);
                kalkulator.angka8.setBackground(Color.decode("#25262A"));
                kalkulator.angka8.setForeground(Color.WHITE);
                kalkulator.angka9.setBackground(Color.decode("#25262A"));
                kalkulator.angka9.setForeground(Color.WHITE);
                kalkulator.titik.setBackground(Color.decode("#25262A"));
                kalkulator.titik.setForeground(Color.WHITE);
                kalkulator.btnBagi.setBackground(Color.decode("#AB6804"));
                kalkulator.btnBagi.setForeground(Color.WHITE);
                kalkulator.kali.setBackground(Color.decode("#AB6804"));
                kalkulator.kali.setForeground(Color.WHITE);
                kalkulator.tambah.setBackground(Color.decode("#AB6804"));
                kalkulator.tambah.setForeground(Color.WHITE);
                kalkulator.kurang.setBackground(Color.decode("#AB6804"));
                kalkulator.kurang.setForeground(Color.WHITE);
                kalkulator.samadengan.setBackground(Color.decode("#1D884D"));
                kalkulator.samadengan.setForeground(Color.WHITE);
            }
        });
        
        
    }
    
    
    public String fixKata(String kata){
        String fixKata = kata;
        if(kata.charAt(kata.length()-1) == '.'){
            fixKata = kata.substring(0,kata.length() -1);
        }
        return fixKata;
    }
    
    public void setAngka(String angka){      
        //limit hanya satu parameter yang bisa ditambahkan
        
        String current;
        boolean koma = false;
        if (lengthInput == 0) {
            current = angka;
            if(angka == ".") current = "0.";
            //mengecek jika terdapat operator pada input pertama
            if(Arrays.asList(operator).contains(angka)) return;
        }else{
            //handle untuk multiple operator ==>
             if (Arrays.asList(operator).contains(angka)) {
                int lastIndex  = Output.getText().length() - 1;
                String stringLast = String.valueOf(Output.getText().charAt(lastIndex));
                if (Arrays.asList(operator).contains(stringLast)) return;
                
                //melimit hanya ada dua operasi saja
                if(jumOperator > 0) return;  
                jumOperator++;
            }
            // <===
            //untuk menghandle multiple koma ==>
            if(angka == ".") {
                if(Output.getText().charAt(Output.getText().length() - 1) == '.'){
                        koma = true;
                }
            }
            // <==
            current = Output.getText().toString();
            //mendiseble ketika ada multiple koma <>
            if(koma)current = current +="";
            else 
                current += angka;
        }
        lengthInput++;
        Output.setText(current);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Output;
    private javax.swing.JButton angka0;
    private javax.swing.JButton angka1;
    private javax.swing.JButton angka2;
    private javax.swing.JButton angka3;
    private javax.swing.JButton angka4;
    private javax.swing.JButton angka5;
    private javax.swing.JButton angka6;
    private javax.swing.JButton angka7;
    private javax.swing.JButton angka8;
    private javax.swing.JButton angka9;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton titik;
    // End of variables declaration//GEN-END:variables
}
